name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-studio:
    uses: ./.github/workflows/Build.CelesteStudio.yml
    with:
      build-cfg: Release
  
  release:
    runs-on: ubuntu-latest
    needs: build-studio

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
            
      - name: Download Windows x64
        uses: actions/download-artifact@v4
        with:
          name: CelesteStudio-windows-x64
          path: CelesteStudio-windows-x64
      - name: Download Linux x64
        uses: actions/download-artifact@v4
        with:
          name: CelesteStudio-linux-x64
          path: CelesteStudio-linux-x64
      - name: Download OSX x64
        uses: actions/download-artifact@v4
        with:
          name: CelesteStudio-osx-x64
          path: CelesteStudio-osx-x64

      # download-artifact automatically unzips them, so we need to re-zip
      - name: Re-zip artifacts
        run: |
          pushd CelesteStudio-windows-x64
          zip CelesteStudio-windows-x64.zip **
          popd
          pushd CelesteStudio-linux-x64
          zip CelesteStudio-linux-x64.zip **
          popd
          pushd CelesteStudio-osx-x64
          zip CelesteStudio-osx-x64.zip CelesteStudio.Mac.app
          popd
      
      - name: Fill-in release info
        run: |
          sed -i "s/##STUDIO_VERSION##/{{ github.ref_name }}/" CelesteTAS-EverestInterop/EverestInterop/StudioHelper.cs
          sed -i "s/##URL_WINDOWS_x64##/https:\/\/github.com\/{{ github.repository }}\/releases\/download\/{{ github.ref_name }}\/CelesteStudio-windows-x64.zip/" CelesteTAS-EverestInterop/EverestInterop/StudioHelper.cs
          sed -i "s/##URL_LINUX_x64##/https:\/\/github.com\/{{ github.repository }}\/releases\/download\/{{ github.ref_name }}\/CelesteStudio-linux-x64.zip/" CelesteTAS-EverestInterop/EverestInterop/StudioHelper.cs
          sed -i "s/##URL_OSX_x64##/https:\/\/github.com\/{{ github.repository }}\/releases\/download\/{{ github.ref_name }}\/CelesteStudio-osx-x64.zip/" CelesteTAS-EverestInterop/EverestInterop/StudioHelper.cs
          sed -i "s/##CHECKSUM_WINDOWS_x64##/$(md5sum CelesteStudio-windows-x64/CelesteStudio-windows-x64.zip | head -c 32)/" CelesteTAS-EverestInterop/EverestInterop/StudioHelper.cs
          sed -i "s/##CHECKSUM_LINUX_x64##/$(md5sum CelesteStudio-linux-x64/CelesteStudio-linux-x64.zip | head -c 32)/" CelesteTAS-EverestInterop/EverestInterop/StudioHelper.cs
          sed -i "s/##CHECKSUM_OSX_x64##/$(md5sum CelesteStudio-osx-x64/CelesteStudio-osx-x64.zip | head -c 32)/" CelesteTAS-EverestInterop/EverestInterop/StudioHelper.cs

      - name: Build
        run: dotnet build CelesteTAS-EverestInterop -c Release -p:DefineConstants=INSTALL_STUDIO
          
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            CelesteTAS-EverestInterop.zip 
            CelesteStudio-windows-x64/CelesteStudio-windows-x64.zip
            CelesteStudio-linux-x64/CelesteStudio-linux-x64.zip
            CelesteStudio-osx-x64/CelesteStudio-osx-x64.zip
